import { describe, expect, it } from "vitest";
import { MLB_TEAMS } from "../src/teams";

describe("MLB team data", () => {
  it("contains all 30 MLB teams with the expected static data", () => {
    expect(MLB_TEAMS).toEqual([
      {
        id: 110,
        name: "Baltimore Orioles",
        abbreviation: "BAL",
        league: "AL",
        division: "East",
      },
      {
        id: 111,
        name: "Boston Red Sox",
        abbreviation: "BOS",
        league: "AL",
        division: "East",
      },
      {
        id: 147,
        name: "New York Yankees",
        abbreviation: "NYY",
        league: "AL",
        division: "East",
      },
      {
        id: 139,
        name: "Tampa Bay Rays",
        abbreviation: "TB",
        league: "AL",
        division: "East",
      },
      {
        id: 141,
        name: "Toronto Blue Jays",
        abbreviation: "TOR",
        league: "AL",
        division: "East",
      },
      {
        id: 145,
        name: "Chicago White Sox",
        abbreviation: "CWS",
        league: "AL",
        division: "Central",
      },
      {
        id: 114,
        name: "Cleveland Guardians",
        abbreviation: "CLE",
        league: "AL",
        division: "Central",
      },
      {
        id: 116,
        name: "Detroit Tigers",
        abbreviation: "DET",
        league: "AL",
        division: "Central",
      },
      {
        id: 118,
        name: "Kansas City Royals",
        abbreviation: "KC",
        league: "AL",
        division: "Central",
      },
      {
        id: 142,
        name: "Minnesota Twins",
        abbreviation: "MIN",
        league: "AL",
        division: "Central",
      },
      {
        id: 117,
        name: "Houston Astros",
        abbreviation: "HOU",
        league: "AL",
        division: "West",
      },
      {
        id: 108,
        name: "Los Angeles Angels",
        abbreviation: "LAA",
        league: "AL",
        division: "West",
      },
      {
        id: 133,
        name: "Athletics",
        abbreviation: "ATH",
        league: "AL",
        division: "West",
      },
      {
        id: 136,
        name: "Seattle Mariners",
        abbreviation: "SEA",
        league: "AL",
        division: "West",
      },
      {
        id: 140,
        name: "Texas Rangers",
        abbreviation: "TEX",
        league: "AL",
        division: "West",
      },
      {
        id: 144,
        name: "Atlanta Braves",
        abbreviation: "ATL",
        league: "NL",
        division: "East",
      },
      {
        id: 146,
        name: "Miami Marlins",
        abbreviation: "MIA",
        league: "NL",
        division: "East",
      },
      {
        id: 121,
        name: "New York Mets",
        abbreviation: "NYM",
        league: "NL",
        division: "East",
      },
      {
        id: 143,
        name: "Philadelphia Phillies",
        abbreviation: "PHI",
        league: "NL",
        division: "East",
      },
      {
        id: 120,
        name: "Washington Nationals",
        abbreviation: "WSH",
        league: "NL",
        division: "East",
      },
      {
        id: 112,
        name: "Chicago Cubs",
        abbreviation: "CHC",
        league: "NL",
        division: "Central",
      },
      {
        id: 113,
        name: "Cincinnati Reds",
        abbreviation: "CIN",
        league: "NL",
        division: "Central",
      },
      {
        id: 158,
        name: "Milwaukee Brewers",
        abbreviation: "MIL",
        league: "NL",
        division: "Central",
      },
      {
        id: 134,
        name: "Pittsburgh Pirates",
        abbreviation: "PIT",
        league: "NL",
        division: "Central",
      },
      {
        id: 138,
        name: "St. Louis Cardinals",
        abbreviation: "STL",
        league: "NL",
        division: "Central",
      },
      {
        id: 109,
        name: "Arizona Diamondbacks",
        abbreviation: "AZ",
        league: "NL",
        division: "West",
      },
      {
        id: 115,
        name: "Colorado Rockies",
        abbreviation: "COL",
        league: "NL",
        division: "West",
      },
      {
        id: 119,
        name: "Los Angeles Dodgers",
        abbreviation: "LAD",
        league: "NL",
        division: "West",
      },
      {
        id: 135,
        name: "San Diego Padres",
        abbreviation: "SD",
        league: "NL",
        division: "West",
      },
      {
        id: 137,
        name: "San Francisco Giants",
        abbreviation: "SF",
        league: "NL",
        division: "West",
      },
    ]);
  });
});
